Moved artifact storage settings into build-acp
This makes it easier to override ARTIFACTS_* variables at runtime

diff --git a/base/bin/build-acp b/base/bin/build-acp
--- a/base/bin/build-acp
+++ b/base/bin/build-acp
@@ -8,12 +8,28 @@
 # Abort if anything failse
 set -e
 
+if [[ "${AWS_ACCESS_KEY_ID}" == "" ]] || [[ "${AWS_SECRET_ACCESS_KEY}" == "" ]] || [[ "${ARTIFACTS_BUCKET_NAME}" == "" ]]; then
+	echo "Cannot upload artifacts."
+	echo "Please make sure AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and ARTIFACTS_BUCKET_NAME environment variables are configured."
+	exit 1
+fi
+
+# Configure ARTIFACTS_BASE_URL, unless it has been already defined
+ARTIFACTS_BASE_URL=${ARTIFACTS_BASE_URL:-"https://${ARTIFACTS_BUCKET_NAME}.s3.amazonaws.com"}
+# Configure ARTIFACTS_BUCKET_PATH, unless it has been already defined
+ARTIFACTS_BUCKET_PATH=${ARTIFACTS_BUCKET_PATH:-"${REPO_NAME_SAFE}/${BRANCH_NAME_SAFE}-${GIT_COMMIT_HASH}"}
+# Configure ARTIFACTS_URL, unless it has been already defined
+# By default expecting index.html as the default entry point into the bucket/path
+ARTIFACTS_URL=${ARTIFACTS_URL:-"${ARTIFACTS_BASE_URL}/${ARTIFACTS_BUCKET_PATH}/index.html"}
+
+# Sync source locally
+source=${1}
+# Sync destination on S3
+destination="s3/${ARTIFACTS_BUCKET_NAME}/${ARTIFACTS_BUCKET_PATH}"
+
 # Initialize minio client (mc) configuration for S3
 # AWS API keys must be set in the build settings
 mc config host add s3 https://s3.amazonaws.com ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY}
-
-source=${1}
-destination="s3/${ARTIFACTS_BUCKET_NAME}/${ARTIFACTS_BUCKET_PATH}"
 
 # Create bucket if it does not exist
 mc mb "s3/${ARTIFACTS_BUCKET_NAME}"
diff --git a/base/bin/build-env b/base/bin/build-env
--- a/base/bin/build-env
+++ b/base/bin/build-env
@@ -5,8 +5,8 @@
 #
 # Usage source build-env
 
-# Abort if anything fails
-set -e
+set -e # Abort if anything fails
+#set -x # Echo commands
 
 # -------------------- Constants -------------------- #
 
@@ -119,23 +119,6 @@ sandbox_server_env ()
 	fi
 }
 
-# Set environment variables for artifact storage functionality
-artifact_storage_env ()
-{
-	if [[ "$ARTIFACTS_BUCKET_NAME" == "" ]]; then
-		echo "Cannot upload artifacts. ARTIFACTS_BUCKET_NAME environment variable is not set."
-		exit
-	fi
-
-	# Configure ARTIFACTS_BUCKET_PATH, unless it has been already defined
-	export ARTIFACTS_BUCKET_PATH=${ARTIFACTS_BUCKET_PATH:-"${REPO_NAME_SAFE}/${BRANCH_NAME_SAFE}-${GIT_COMMIT_HASH}"}
-	# Configure ARTIFACTS_BASE_URL, unless it has been already defined
-	export ARTIFACTS_BASE_URL=${ARTIFACTS_BASE_URL:-"https://${ARTIFACTS_BUCKET_NAME}.s3.amazonaws.com"}
-	# Configure ARTIFACTS_URL, unless it has been already defined
-	# By default expecting index.html as the default entry point into the bucket/path
-	export ARTIFACTS_URL=${ARTIFACTS_URL:-"${ARTIFACTS_BASE_URL}/${ARTIFACTS_BUCKET_PATH}/index.html"}
-}
-
 # -------------------- Runtime -------------------- #
 
 echo "Configuring build settings..."
@@ -151,7 +134,3 @@ git_env
 # Sandbox server settings
 echo "Configuring sandbox server settings..."
 sandbox_server_env
-
-# Artifact storage
-echo "Configuring artifact storage settings..."
-artifact_storage_env
