Bail if invalid codebase method specified.

diff --git a/base/bin/build-init b/base/bin/build-init
--- a/base/bin/build-init
+++ b/base/bin/build-init
@@ -2,6 +2,11 @@
 
 # This script sets up a sandbox environment for the build on the remote docker host.
 
+if [[ "${REMOTE_CODEBASE_METHOD}" != "rsync" ]] || [[ "${REMOTE_CODEBASE_METHOD}" != "git" ]]; then
+	echo "Only rsync and git codebase methods are supported. ${REMOTE_CODEBASE_METHOD} method given. Aborting."
+	exit 1
+fi
+
 # Collect information surrounding the existence of the remote build directory,
 # and whether or not it is a Git repository.
 ssh docker-host "[ -d $REMOTE_BUILD_DIR ]"
