rsync sources from agent to server
This eliminates git as a host level dependency on the sandbox server

diff --git a/base/bin/build-init b/base/bin/build-init
--- a/base/bin/build-init
+++ b/base/bin/build-init
@@ -2,6 +2,9 @@
 
 # This script sets up a sandbox environment for the build on the remote docker host.
 
+set -e # Abort if anything fails
+#set -x # Echo commands
+
 # Cleanup
 echo "Setting up remote build environment..."
 ssh docker-host "(cd $REMOTE_BUILD_DIR && fin rm -f 2>/dev/null) || true"
@@ -9,8 +12,13 @@ ssh docker-host "sudo rm -rf $REMOTE_BUILD_DIR 2>/dev/null; mkdir -p $REMOTE_BUI
 
 # Note: build-exec = ssh docker-host "cd $REMOTE_BUILD_DIR && ($@)"
 
-# Checkout sources
-build-exec "git clone --branch="$GIT_BRANCH_NAME" --depth 50 $GIT_REPO_URL . && git reset --hard $GIT_COMMIT_HASH && ls -la"
+# Checkout sources on the remote host
+#echo "Checking out codebase via git..."
+#build-exec "git clone --branch="$GIT_BRANCH_NAME" --depth 50 $GIT_REPO_URL . && git reset --hard $GIT_COMMIT_HASH && ls -la"
+
+# Rsync sources to the remote host
+echo "Syncing codebase via rsync..."
+rsync --delete -az ${BUILD_DIR}/ docker-host:${REMOTE_BUILD_DIR}
 
 # Configure sandbox settings
 echo "Configuring sandbox settings..."
