Keep cleanup and checkout logic separated.

diff --git a/base/bin/build-init b/base/bin/build-init
--- a/base/bin/build-init
+++ b/base/bin/build-init
@@ -2,25 +2,39 @@
 
 # This script sets up a sandbox environment for the build on the remote docker host.
 
+# Collect information surrounding the existence of the remote build directory,
+# and whether or not it is a Git repository.
+ssh docker-host "[ -d $REMOTE_BUILD_DIR ]"
+remote_build_dir_exists_check_result=$?
+ssh docker-host "[ -d $REMOTE_BUILD_DIR/.git ]"
+remote_git_check_result=$?
+
 set -e # Abort if anything fails
 #set -x # Echo commands
 
-# Cleanup
-echo "Setting up remote build environment..."
-if [[ "${REMOTE_BUILD_DIR_CLEANUP}" == "1" ]] || [[ "${REMOTE_CODEBASE_METHOD}" == "rsync" ]]; then
-	echo "Re-initializing remote environment from scratch..."
-	[[ "${REMOTE_BUILD_DIR_CLEANUP}" == "0" ]] && [[ "${REMOTE_CODEBASE_METHOD}" == "rsync" ]] && echo "rsync is not supported for preserved builds!"
+# Cleanup under the following conditions:
+# 1) REMOTE_BUILD_DIR_CLEANUP is set to 1.
+# 2) rsync is the supported method of transferring the codebase.
+# 3) git is the supported method but the remote directory either doesn't exist
+#    or is not a git repository, signaling a possible build method switch from
+#    rsync -> git, or the directory was somehow created outside of the agent's
+#    purview.
+# 4) git is the supported method but the remote build directory does not exist yet.
+echo "Cleaning up remote build environment..."
+if [[ "${REMOTE_BUILD_DIR_CLEANUP}" == "1" ]] ||
+	[[ "${REMOTE_CODEBASE_METHOD}" == "rsync" ]] ||
+	([[ "${REMOTE_CODEBASE_METHOD}" == "git" ]] && [[ $remote_git_check_result != 0 ]]) ||
+	([[ "${REMOTE_CODEBASE_METHOD}" == "git" ]] && [[ $remote_build_dir_exists_check_result != 0 ]]); then
+	echo "Cleanup is re-initializing the remote environment..."
 	ssh docker-host "(cd ${REMOTE_BUILD_DIR} 2>/dev/null && fin rm -f 2>/dev/null) || true"
 	ssh docker-host "sudo rm -rf ${REMOTE_BUILD_DIR} 2>/dev/null; mkdir -p ${REMOTE_BUILD_DIR}"
 else
-	echo "Cleanup disabled, only applying new changes on remote environment..."
-	# Ensure directory exists. 
-	ssh docker-host "mkdir -p ${REMOTE_BUILD_DIR}"
+	echo "Cleanup is preserving the build environment."
 fi
 
 # Note: build-exec = ssh docker-host "cd $REMOTE_BUILD_DIR && ($@)"
 
-# Remote codebase initialization method. Either 'git' (default) or 'rsync'
+# Remote codebase initialization method. Either 'rsync' (default) or 'git'
 if [[ "${REMOTE_CODEBASE_METHOD}" == "rsync" ]]; then
 	# Rsync sources to the remote host
 	echo "Syncing codebase via rsync..."
@@ -28,10 +42,13 @@ if [[ "${REMOTE_CODEBASE_METHOD}" == "rsync" ]]; then
 else
 	# Checkout sources on the remote host
 	echo "Checking out codebase via git..."
-	if [[ "${REMOTE_BUILD_DIR_CLEANUP}" == "1" ]]; then
-		build-exec "git clone --branch="${GIT_BRANCH_NAME}" --depth 50 ${GIT_REPO_URL} . && git reset --hard ${GIT_COMMIT_HASH} && ls -la"
+	if [[ $remote_git_check_result == 0 ]] && [[ "${REMOTE_BUILD_DIR_CLEANUP}" == "0" ]]; then
+		# Remote directory is confirmed to be a git repository and we are
+		# preserving the build, so we can safely fetch and reset.
+		build-exec "git fetch origin && git reset --hard origin/$GIT_BRANCH_NAME && ls -la"
 	else
-		build-exec "(git fetch origin && git reset --hard origin/$GIT_BRANCH_NAME && ls -la) || (git clone --branch="${GIT_BRANCH_NAME}" --depth 50 ${GIT_REPO_URL} . && git reset --hard ${GIT_COMMIT_HASH} && ls -la)"
+		# Remote directory is not a git repository.
+		build-exec "git clone --branch="${GIT_BRANCH_NAME}" --depth 50 ${GIT_REPO_URL} . && git reset --hard ${GIT_COMMIT_HASH} && ls -la"
 	fi
 fi
 
@@ -77,3 +94,5 @@ if [[ "${secrets}" != "" ]]; then
 		build-exec "fin config set $secret='${!secret}' --env=local >/dev/null"
 	done
 fi
+
+set +e
